version: '3'
networks:
  app-network:
    driver: bridge
services:
  database:
    image: mysql:8.0
    env_file: ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: sh -c "
      ./wait-for-it.sh database:3306 --timeout=60 &&
      npx sequelize-cli db:migrate &&
      npm start"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - backend
volumes:
  db-data: